name: GitHub Actions Demo
on:
  push:
     branches: [main]
     paths-ignore: [.github/..]
  pull_request:
     branches: [main]
  schedule:
     - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job triggered is: ${{ github.event_name }}"
          echo "The branch name is: ${{ github.ref }}"
      - uses: actions/checkout@v4
      - run: |
          echo "List of all files:"
          tree
    
    
