name: CI Docker Demo
on:
  push: 
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-my-docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@tperaltab'

      - name: Output action Date and Time
        run: echo "${{ steps.hello-action.outputs.time }}"
